### PR TITLE
Added onPreviewStarted event and fixed some issues

### PR DESCRIPTION
**Pull request by Ninjaman494**
Related issues: [#29](https://github.com/gogopop/CameraKit-Android/issues/29) [#92](https://github.com/gogopop/CameraKit-Android/issues/92) [#68](https://github.com/gogopop/CameraKit-Android/issues/68)

I also added an onPreviewStarted event to CameraListener which gets called when the Camera Preview has been drawn. In my app, I need a timer to start once the camera is displayed, so I needed this event to achieve this.

This is my first pull request, so if I did something wrong I apologize.

### CODE REVIEW

**Comment by andreas-** [comment]
+1

**Comment by Ninjaman494** [comment]
Orientation fix is the same as the one in this PR: #156

**Comment by austinkettner** [comment]
Closing until a merge conflict resolution commit is in! Happy to merge is and reOpen this once available =)

**Comment by Ninjaman494** [comment]
Sorry for the late response, it's been awhile since I've looked at this repo. I've fixed the merge conflicts and changed my implementation to work with the new Event system.

**Comment by austinkettner** [comment]
Reviewing and will hopefully merge soon @Ninjaman494

**Comment by austinkettner** [comment]
In favor of our massive refactor, if this issue still persist please make a new PR using the refined codebase. We definitely appreciate the help though! Just limiting merge conflicts and gathering support of testing/refinement/comments/feedback on the 1.0.0 PR.

https://github.com/CameraKit/camerakit-android/pull/318

**Pull request closed without merging**
