### PR TITLE
Release v0.13.6

### PR DESCRIPTION
**Pull request by austinkettner**

### CODE REVIEW

**Comment by nullptr2this** [comment]
@austinkettner Wow, quick turn around on that PR.  Thanks.  I've actually got another one coming that might solve this one: https://github.com/CameraKit/camerakit-android/issues/385

There is a similar issue with orientation when either switching to or starting out in landscape mode.

**Comment by austinkettner** [comment]
@nullptr2this nice! Thanks for the heads up, feel free to ref this branch and I can integrate it in before merging.

**Comment by nullptr2this** [comment]
@austinkettner Is a potential 0.13.6 release going against the grain in terms of the beta work that is ongoing?  I really need video and so have been focusing on the 0.13.x stuff.  Trying to determine which way to go in terms of potentially getting some of these updates in, if they are accepted, or deploying from my own fork because of timing.

**Comment by austinkettner** [comment]
We totally understand the need for video + photo and as such have been extending support to the 0.13.x line while the v1.0.0-beta line takes an enormous amount of time to ship. Issuing a 0.13.6 doesn't conflict with our beta work and we intend to keep patching 0.13.x until a final v1.0.0 is out the door, so I think we are safe!

Any changes you make and PR, that we include in this 0.13.6 release, will be available very quickly via Bintray once the release is tagged/merged.

**Comment by nullptr2this** [comment]
@austinkettner Sweet. Thanks for the quick response. Once I get past some of this stuff I am doing that requires 0.13.6 I'll try to jump over and help out on the beta a little when/where I can.  Again, thanks!!!

**Comment by austinkettner** [comment]
No problem! @nullptr2this 

Are the latest commits I just merged into this PR (from your PR) the final changes you needed in 0.13.6?

**Comment by nullptr2this** [comment]
@austinkettner Ha.  Yeah, the answer to that question is ...maybe...depending on the way things go with some feature discussions for what we are doing I may or may not submit a PR for enabling/disabling the use of physical device orientation to determine if capture should be rotated if UI is locked in one orientation and the user holds the device in another.  That would be augmentation rather than a fix though.  Not sure if that is something that should be submitted for a 0.13.x type of build.  If not, that is something I can manage in a fork if I need it.  Those things I submitted so far seem generally useful fixes though, so...

**Comment by andreififiita** [comment]
Hello, what is the correct way to use the librari in gradle?
if I try     implementation 'com.camerakit:camerakit:0.13.6' (or 0.13.5) I get "ERROR: Failed to resolve: com.camerakit:camerakit:0.13.6"

**Comment by nullptr2this** [comment]
@andreififiita The 0.13.6 release has not been merged and distributed via bintray yet, so you will not be able to get ahold of it via gradle unless you set up your own artifact management.

**Comment by andreififiita** [comment]
> @andreififiita The 0.13.6 release has not been merged and distributed via bintray yet, so you will not be able to get ahold of it via gradle unless you set up your own artifact management.
> 

Ok, but how about 0.13.5? I get the same error. What am I doing wrong?

**Comment by nullptr2this** [comment]
@andreififiita The 0.x.x version of the library operated under a different group ID.  Use com.wonderkiln:camerakit:0.13.5

**Comment by andreififiita** [comment]
> @andreififiita The 0.x.x version of the library operated under a different group ID. Use com.wonderkiln:camerakit:0.13.5

Thank you very much! Are there any other dependencies that are needed?

**Comment by nullptr2this** [comment]
@andreififiita Gradle should pull transitive dependencies for you.

**Pull request merged**
