### PR TITLE
Ability to set max video recording duration

### PR DESCRIPTION
**Pull request by lucianoiam**
Added support for setting max video recording duration through MediaRecorder setMaxDuration() method. Updated project to compile on Android Studio 3.2.1 and AndroidX support libraries.

Changes required to integrate CameraKit into company app: https://play.google.com/store/apps/details?id=wink.wonder.fbprofilevideo

### CODE REVIEW

**Comment by lucianoiam** [comment]
Hi, this is a minor patch that exposes a must-have MediaRecorder feature for our app. Do you think it is possible to merge it to the main release? this way we can stop working on a custom fork. Included in the PR is a bugfix related to custom output file path, and migration to AS 3.2.1 + AndroidX, I noticed a newer pull request also calls for this migration which is needed for new projects. Thanks for creating this great project.

**Comment by austinkettner** [comment]
Hey @lucianoiam thanks for following up on this. We are figuring out how best to manage this, and may request a change or two ahead of merging, but will get back to in the next 48hours.

Thanks for contributing to CameraKit =)

**Comment by lucianoiam** [comment]
That sounds great! thanks for the update

**Comment by austinkettner** [comment]
@lucianoiam We have discussed this and are going to issue a new PR into master containing these changes plus a few others. While we love that you took the time to make these awesome changes that help CameraKit fit your needs we aren't in a good position to get signed Contributor License Agreements at the moment, so we are being cautious. We absolutely appreciate your effort here and we will be implementing all these changes just via our team, this week.

This new release will be `0.13.3` and it will be live and usable by end of this week. @emersoncloud will be updating this PR once the new PR is ready to merge and closing it once merged. Ideally we can get you to test it ahead of time to make sure all bases are covered =)

**Comment by lucianoiam** [comment]
Sounds great. Being able to use an unmodified version of CK is a huge improvement already, I am happy to have contributed either with code or just feedback. Count me in for testing if needed, thanks !

**Comment by emersoncloud** [comment]
@lucianoiam thanks again for the contributions. We've just merged the v0.13.3 branch into master, and you should now be able to include it in your project!

**Comment by lucianoiam** [comment]
Works perfectly, thanks for keeping this great project going.

**Pull request closed without merging**
